export const Config = {
    alphabetonly : /^[a-zA-Z\s]*$/,
    admin: 'Admins',
    storeOwners: 'Store Owners',
    addAdmin: 'Add Admin',
    addStoreOwner: 'Add Store Owner', 
    newStoreOwner: 'New Store Owner',
    newAdmin: 'New Admin',
    updateStoreOwner: 'Update Store Owner',
    save: 'save',
    update: 'update',
    updateAdmin: 'Update Admin',
    market: 'MARKET',
    myStores:'My Stores',
    newStore: 'New Store',
    storeName: 'Store Name',
    updateStore: 'Update Store',
    buy: 'Buy',
    pay: 'Pay',
    createProduct: 'New Product',
    updateProduct: 'Edit Product',
    completeTransaction: 'Transaction completed'
}
